apiVersion: v1
kind: Service
metadata:
  name: ecom-ui-service
  labels:
    app: ecom-ui
spec:
  type: NodePort
  selector:
    app: ecom-ui
  ports:
  - port: 8880
    targetPort: 80
    nodePort: 31001
