apiVersion: v1
kind: Service
metadata:
  name: app-nginx-loadbalancer-service
  namespace: test
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: https
    port: 8070
    targetPort: 80
