apiVersion: v1
kind: Service
metadata:
  name: app-nginx-loadbalancer-service
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 8090
    targetPort: 80
